# Generated by Django 2.0.5 on 2018-07-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxservice', '0002_auto_20180624_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='订单金额')),
                ('out_trade_no', models.CharField(max_length=32, verbose_name='自主生成的订单号')),
                ('payjs_order_id', models.CharField(max_length=32, verbose_name='payjs 的订单号')),
                ('transaction_id', models.CharField(max_length=32, verbose_name='微信用户手机显示的订单号')),
                ('time_end', models.CharField(max_length=32, verbose_name='支付成功时间')),
                ('openid', models.CharField(max_length=64, verbose_name='用户OPENID标志')),
                ('attach', models.CharField(max_length=250, verbose_name='用户自定义数据')),
                ('mchid', models.CharField(max_length=24, verbose_name='payjs 商户号')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='oder',
            field=models.CharField(default='', max_length=32, verbose_name='订单号'),
        ),
    ]
