# Generated by Django 2.0.5 on 2018-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxservice', '0003_auto_20180703_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge_oder',
            name='attach',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='用户自定义数据'),
        ),
    ]
