# Generated by Django 2.0.5 on 2018-07-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxservice', '0006_auto_20180703_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='oder',
            new_name='order',
        ),
    ]
