# Generated by Django 2.0.5 on 2018-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('application', models.CharField(max_length=50, verbose_name='应聘职位')),
                ('applyTime', models.CharField(max_length=20, verbose_name='申请时间')),
                ('applyCompany', models.CharField(max_length=20, verbose_name='应聘公司')),
                ('match', models.CharField(max_length=5, verbose_name='匹配程度')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='居住地')),
                ('status', models.CharField(max_length=20, verbose_name='求职状态')),
                ('gender', models.CharField(choices=[('Male', '男'), ('Female', '女')], max_length=6, verbose_name='性别')),
                ('birth', models.CharField(max_length=20, verbose_name='出生日期')),
                ('workExperiod', models.CharField(max_length=15, verbose_name='工作经验')),
                ('resumeID', models.CharField(max_length=15, verbose_name='简历ID')),
                ('resident', models.CharField(max_length=50, verbose_name='户籍')),
                ('income', models.CharField(max_length=50, verbose_name='目前年收入')),
                ('self_evaluation', models.CharField(max_length=250, verbose_name='自我评价')),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workExperience', models.TextField(verbose_name='工作经验')),
                ('projectExprience', models.TextField(verbose_name='项目经验')),
                ('education', models.TextField(verbose_name='教育经历')),
            ],
            options={
                'verbose_name': '相关经历',
                'verbose_name_plural': '相关经历',
            },
        ),
        migrations.CreateModel(
            name='wantJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectSalary', models.CharField(max_length=10, verbose_name='期望薪资')),
                ('address', models.CharField(max_length=20, verbose_name='期望工作地点')),
                ('position', models.CharField(max_length=20, verbose_name='求职岗位')),
                ('busi', models.CharField(max_length=20, verbose_name='期望行业')),
                ('joinTime', models.CharField(max_length=20, verbose_name='到岗时间')),
                ('workType', models.CharField(max_length=5, verbose_name='工作类型')),
            ],
            options={
                'verbose_name': '求职意向',
                'verbose_name_plural': '求职意向',
            },
        ),
    ]
