# Generated by Django 2.0.5 on 2018-05-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantjob',
            name='baseInfo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='resume.BaseInfo', verbose_name='基本信息'),
        ),
    ]
