# Generated by Django 2.0.5 on 2018-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20180609_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantjob',
            name='expectSalary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='期望薪资'),
        ),
    ]
