# Generated by Django 2.0.5 on 2018-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20180609_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantjob',
            name='busi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='期望行业'),
        ),
        migrations.AlterField(
            model_name='wantjob',
            name='joinTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='到岗时间'),
        ),
        migrations.AlterField(
            model_name='wantjob',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='求职岗位'),
        ),
        migrations.AlterField(
            model_name='wantjob',
            name='workType',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='工作类型'),
        ),
    ]
